# Site Settings
title:
description: >-
 In todayâ€™s world a focus on preparing for the issues of tomorrow is what separates secure organizations from becoming headlines.
baseurl: "" # leave empty for user/org pages
url: "https://JustinGold-infosec.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author info
author:
  name: Justin Gold
  email: # your email (optional)
  linkedin: # your linkedin username (optional)
  github: JustinGold-infosec

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
